version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 82:80
        #- 443:443
    volumes:
      - /home/ubuntu/webapp/nginx:/etc/nginx
        #- <path/to/your/certs>:/etc/ssl/private
